import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { PackageOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, ProductCard, VisitBand } from "@/components/bakery-ui";
import { menuCategories, products, type ProductCategory } from "@/lib/bakery-data";

export const Route = createFileRoute("/menu")({ head: () => ({ meta: [{ title: "Bakery Menu in Dinanagar | Sharma Bakery" }, { name: "description", content: "Browse confirmed products from Sharma Bakery and enquire for current availability and prices." }, { property: "og:title", content: "Bakery Menu — Sharma Bakery Dinanagar" }, { property: "og:description", content: "A clear, editable catalogue showing only products confirmed by the bakery." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/menu" }] }), component: MenuPage });
function MenuPage() { const [filter, setFilter] = useState<"All" | ProductCategory>("All"); const visible = products.filter((p) => filter === "All" || p.category === filter); return <><PageIntro eyebrow="Bakery menu" title="Browse what’s currently confirmed" text="Prices and availability can change. Please enquire directly before visiting or ordering." /><section className="section-space"><div className="page-wrap"><div className="flex flex-wrap gap-2" role="group" aria-label="Filter menu">{menuCategories.map((category) => <Button key={category} variant={filter === category ? "default" : "outline"} onClick={() => setFilter(category)}>{category}</Button>)}</div><div className="mt-10">{visible.length ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visible.map((product) => <ProductCard key={product.name} product={product} />)}</div> : <div className="border border-dashed border-border bg-secondary/30 px-6 py-16 text-center"><PackageOpen className="mx-auto size-9 text-primary" /><h2 className="mt-4 font-display text-2xl">Catalogue awaiting confirmation</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">No products in this category have been confirmed yet. Contact the bakery to ask what is currently available.</p></div>}</div></div></section><VisitBand /></>; }
